### ISSUE TITLE
Travis CI

### ISSUE THREAD

**Issue by math07** [shinnok/johnny#103]
I'd like to set up a CI like travis-ci just for the fun of learning and understand what this tool can offer to a project. 

It's not really useful for johnny since it doesn't have unit tests but we could compile against different versions of qt and check if our code breaks old qt support as Solar requested. It would also have been cool if travis-ci supported windows but it only supports linux and os x.

@shinnok Since you are the repo admin, only you can go to the travis-ci website and register the github repo.

**Comment by shinnok** [comment]
This is not important for Johnny at the moment. You can do so with a test Qt project in your account and report back with the results, see how this could be useful for Johnny.

On a side note, how about we take on some of the other issues and slow start towards v2.3? There's still lots to do, figure out...
