### ISSUE TITLE
wpapcap

### ISSUE THREAD

**Issue by gavz** [shinnok/johnny#104]
Conversion failed
python: can't open file 'C:/CrackPass/john/run/wpapcap2john.py': [Errno 2] No such file or directory

**Comment by math07** [comment]
Hi,
I fixed it in eb0fe02. The code was looking for wpapcap2john.py but it seems that the executable name in jumbo is wpapcap2john.
If you see other errors with the 2john script don't hesitate to tell me. Have a great day !
