### ISSUE TITLE
hccap

### ISSUE THREAD

**Issue by gavz** [shinnok/johnny#106]
Sorry for my English, I get an error -> "Conversion failed" , when I process hccap file .
I changed file -> openotherformatfiledialog.cpp so ' << ConversionScript ( "hccap2john", "",
                             QList <ConversionScriptParameter> ()
                                 << ConversionScriptParameter ( "hccap file [s]",
                                                              FILE_PARAM)) s
I watched in the Process monitor hccap2john.exe and for some reason can not find the file hccap and .lst file for save

**Comment by math07** [comment]
Hey gavz,
I looked at JtR's hccap2john.cpp code and the process exits with 1 if a file was converted successfully. In Johnny's code, we assume that the conversion failed if the process exit with a non-zero value. It's supposed to be a unix-shell standard (http://tldp.org/LDP/abs/html/exit-status.html) . However, I don't know if many john2* script doesn't respect this behavior, so maybe we should no more rely on this condition in void OpenOtherFormatFileDialog::conversionFinished(int exitCode,QProcess::ExitStatus exitStatus). What do you want @shinnok ?

**Comment by shinnok** [comment]
Hmm, I'm thinking the long term solution for this is to fix the scripts themselves so that they follow a unified interface. I'm not saying we need to handle them all now, but on a first come first served basis, starting with the hccap one. The 2john utilities should rely on the EXIT_SUCCESS/EXIT_FAILURE defines at least.

**Comment by math07** [comment]
> Hmm, I'm thinking the long term solution for this is to fix the scripts themselves so that they follow a unified interface. I'm not saying we need to handle them all now, but on a first come first served basis, starting with the hccap one. The 2john utilities should rely on the EXIT_SUCCESS/EXIT_FAILURE defines at least.

I agree

**Comment by gavz** [comment]
Thanks very much
