### ISSUE TITLE
error: ‘>>’ should be ‘> >’ within a nested template argument list

### ISSUE THREAD

**Issue by codex8** [shinnok/johnny#108]
`$ qmake && make -j$(nproc)

g++ -c -m64 -pipe -O2 -D_REENTRANT -Wall -W -fPIE -DAPP_VERSION=\"2.2\" -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I. -Isrc -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I. -I. -o main.o src/main.cpp
g++ -c -m64 -pipe -O2 -D_REENTRANT -Wall -W -fPIE -DAPP_VERSION=\"2.2\" -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I. -Isrc -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I. -I. -o mainwindow.o src/mainwindow.cpp
g++ -c -m64 -pipe -O2 -D_REENTRANT -Wall -W -fPIE -DAPP_VERSION=\"2.2\" -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I. -Isrc -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I. -I. -o johnattack.o src/johnattack.cpp
g++ -c -m64 -pipe -O2 -D_REENTRANT -Wall -W -fPIE -DAPP_VERSION=\"2.2\" -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I. -Isrc -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I. -I. -o menu.o src/menu.cpp
g++ -c -m64 -pipe -O2 -D_REENTRANT -Wall -W -fPIE -DAPP_VERSION=\"2.2\" -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I. -Isrc -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I. -I. -o tabwidget.o src/tabwidget.cpp
g++ -c -m64 -pipe -O2 -D_REENTRANT -Wall -W -fPIE -DAPP_VERSION=\"2.2\" -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I. -Isrc -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I. -I. -o johnsession.o src/johnsession.cpp
In file included from src/mainwindow.h:18:0,
                 from src/main.cpp:8:
src/passwordfilemodel.h:53:28: error: ‘>>’ should be ‘> >’ within a nested template argument list
     QVector<QVector<QString>> m_data;
                            ^
In file included from src/mainwindow.h:18:0,
                 from src/mainwindow.cpp:8:
src/passwordfilemodel.h:53:28: error: ‘>>’ should be ‘> >’ within a nested template argument list
     QVector<QVector<QString>> m_data;
                            ^
make: *** [main.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [mainwindow.o] Error 1
`

**Comment by math07** [comment]
If you checkout today's code, it should be fixed by commit 28653b4. I quickly checked that there were no other cases like this in the code base, but if it doesn't work please tell me because I might have missed one.

For the records, contrary to C++0x, some old C++ compilers need a space to make template inside another template work because it finds it ambigous. http://stackoverflow.com/questions/6695261/template-within-template-why-should-be-within-a-nested-template-arg

**Comment by codex8** [comment]
Works :+1:  thanks @math07
