### ISSUE TITLE
CRC Errors whenever I try to unzip 2.1 or 2.2

### ISSUE THREAD

**Issue by Yepitsbroken** [shinnok/johnny#112]
Whenever I try to unzip Johnny 2.1 or 2.2 on windows 10 build 1809 with either the Windows native zip tool or 7zip I get CRC errors.

**Comment by shinnok** [comment]
Hi, I'll test this out when I get my hands on a recent Windows 10.

**Comment by shinnok** [comment]
I assume this is for the release binaries available on the wiki and not the github source release tarballs?

https://openwall.info/wiki/john/johnny

**Comment by shinnok** [comment]
I tested the zip archives for the last 3 releases on Windows 10 latest (and macOS) with the native zip and 7-zip tools and I get no CRC errors. This might have been a 1-time network/disk/software corruption on your side.

Closing this until I find further reason/details to investigate. Thanks for the report.
