### ISSUE TITLE
Installation problems under Ubuntu 18.04.4 LTS

### ISSUE THREAD

**Issue by lw3eov** [shinnok/johnny#114]
Hello, 

I am a new user to Ubuntu 18.04.4 LTS and unable to solve this, please help me as when I follow the instructions you can find at:

https://github.com/shinnok/johnny/blob/v2.2/INSTALL

This happens:

m@m-desktop:~$ sudo apt-get install g++ git qtbase5-dev
[sudo] password for m: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package qtbase5-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
E: Package 'qtbase5-dev' has no installation candidate

Thanks
Regards

Marcelo

**Comment by shinnok** [comment]
Hi Marcelo,

Try installing `qtbase5-dev-tools` instead. Qt package names might differ on different distributions.

**Comment by lw3eov** [comment]
m@m-desktop:~$ sudo apt-get update -y
[sudo] password for m: 
Hit:1 http://ppa.launchpad.net/danielrichter2007/grub-customizer/ubuntu bionic InRelease
Hit:2 http://archive.ubuntu.com/ubuntu bionic InRelease                        
Hit:3 http://ppa.launchpad.net/libreoffice/ppa/ubuntu bionic InRelease         
Hit:4 https://packages.cisofy.com/community/lynis/deb stable InRelease         
Hit:5 https://downloads.iridiumbrowser.de/deb stable InRelease                 
Reading package lists... Done
m@m-desktop:~$ sudo apt-get install -y qtbase5-dev-tools
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package qtbase5-dev-tools is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  qttools5-dev-tools:i386 qttools5-dev-tools

E: Package 'qtbase5-dev-tools' has no installation candidate

**Comment by lw3eov** [comment]
Hi 

I am replying here as I can see that you closed the thread, however I was able to comment but a part of my comment was crossed out automatically (really weird to me), so not sure what happened. I am new in the forum so I still don't know exactly how it works.
Now I get this:
m@m-desktop:~$ sudo apt-get update -y
[sudo] password for m: 
Hit:1 http://ppa.launchpad.net/danielrichter2007/grub-customizer/ubuntu bionic InRelease
Hit:2 http://archive.ubuntu.com/ubuntu bionic InRelease                        
Hit:3 http://ppa.launchpad.net/libreoffice/ppa/ubuntu bionic InRelease         
Hit:4 https://packages.cisofy.com/community/lynis/deb stable InRelease         
Hit:5 https://downloads.iridiumbrowser.de/deb stable InRelease                 
Reading package lists... Done
m@m-desktop:~$ sudo apt-get install -y qtbase5-dev-tools
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package qtbase5-dev-tools is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  qttools5-dev-tools:i386 qttools5-dev-tools

E: Package 'qtbase5-dev-tools' has no installation candidate


    On Wednesday, 1 April 2020, 01:21:47 GMT-3, Shinnok <notifications@github.com> wrote:  
 
 


Hi Marcelo,

Try installing qtbase5-dev-tools instead. Qt package names might differ on different distributions.

**Comment by lw3eov** [comment]
I replaced qtbase5-dev-tools by qttols5-dev-tools amd it solved the problem, thanks
