### ISSUE TITLE
Refactor Settings -  simplify by always saving app settings

### ISSUE THREAD

**Issue by math07** [shinnok/johnny#13]
As proposed by Shinnok, get rid of apply, don't apply, save, don't save, etc.." and automatically save all changes.

**Comment by math07** [comment]
I thought about that yesterday and I think it'll be a really great improvement. Also, we'll make the code simpler in MainWindow since there will be less methods related to settings and I don't think that we'll need to have them as attribute anymore in MainWindow. We will only have a JohnSetting class which will offer get and set to m_settings.value("pathToJohn"); m_settings.setValue("pathToJohn",etc.. We will not store those attributes in JohnSetting class, we will directly access them via QSetting. It'll be a lot easier to understand code-wise

**Comment by shinnok** [comment]
The are some settings which are still considered global though. Like the path to john or the pick interval. Admittedly they do have value in session specific context too, so maybe we should do something about that? Having a session using some john and another a different one or different pick intervals has intrinsic value.

**Comment by shinnok** [comment]
Maybe we could have defaults for those global non-attack settings, also stored via QSettings outside of sessions. A new session copies those values, but allows override.
