### ISSUE TITLE
Redo OS_FORK check in the UI to be similar to the jumbo check

### ISSUE THREAD

**Issue by shinnok** [shinnok/johnny#14]
Thus don't use the define anymore. In JohnProcess the Q_OS_UNIX check should be moved to the cpp in place.

**Comment by shinnok** [comment]
Don't attend to this right now, I'll tell you when it's best to so we don't duplicate work.

**Comment by math07** [comment]
Okay good

**Comment by shinnok** [comment]
@math07 We can do this one now.
