### ISSUE TITLE
Start using JohnHandler

### ISSUE THREAD

**Issue by shinnok** [shinnok/johnny#18]
Take a look at commits between 86ecbf50a602dacc3cb8a8fd3b1bd57061501425 and 8304a345b0d9b383df40e4d29be1922331540703. These implement the JohnHandler class interface that is going to be the base for all future handler wrappers around JtR. A sample implementation has been provided in JohnAttack handler, the main cracking process.

Things to keep in mind regarding the implementation:
* All handler specific functionality that is compute intensive, like post or pre processing of JtR output, should be handled in methods pertaining to that handler class.
* Each JohnHandler has thread affinity to a separate own thread(the moveToThread in the constructor), thus all signal slots connections to and from a JohnHandler should use Qt::QueuedConnection so that we are guaranteed to be honoring the thread affinity.
* All data that is signaled to the UI from a handler should be presented in a fashion readily consumable by the UI code (no compute intensive stuff so that we don't lag in the UI)
* Don't invoke handler methods that are compute intensive or busy wait directly from the UI(i.e. synchronously: handler.exampleMethod()). If you find your self in need of calling slot directly without a meaningful connect() opportunity, please use QMetaObject::invokeMethod() so that we ensure the method is called on the handler's thread.
* I use JohnHandler directly for the simple show and version handlers for now, until we need to expand on their functionality.

What you need to do next is to base HashTypeChecker and the password guessing handler on JohnHandler.

**Comment by math07** [comment]
Done
