### ISSUE TITLE
Decide the platforms for the upcoming release

### ISSUE THREAD

**Issue by shinnok** [shinnok/johnny#21]
We need to start disseminating the upcoming Release. The first step towards coming up with a plan is to ask for feedback from john-dev and john-users lists regarding which platforms should we support for:
1. Source build instructions and testing;
2. Subsequent binary packaging;

For no.2, the installers, let's focus on platforms people are using Johnny on already or express a written desire or need to do so but can't for lack of an installer.

**Comment by math07** [comment]
@shinnok or @AlekseyCherepanov 
Could you please take a look at http://www.openwall.com/lists/john-dev/2015/06/02/26

**Comment by shinnok** [comment]
Support list for 2.0 release:
1. Windows 7 and 8; .msi installer; might include latest jumbo Cygwin build if it's not a hassle; Based on latest Qt5
2. OS X Mavericks and Yosemite; .dmg package; does not include JtR; Based on latest Qt5
3. Linux(Ubuntu, Debian, Mint, Fedora, various distros); source build instructions
4. Compatibility with Qt as low as version 4.6.2 (for old Linuxes and OS X Leopard);

**Comment by shinnok** [comment]
No JtR included for this release.
