### ISSUE TITLE
Tableview, some uncracked pwd not shown

### ISSUE THREAD

**Issue by math07** [shinnok/johnny#22]
Here is the use case.
Imagine the .pot file has some already cracked password in it. If we open a new file, start a new attack or resume another one with a different format, callJohnShow() method call ./john --formatXXX --show pw1.txt. In the tableview, the already cracked password from the .pot file from format YYY won't appears.
1) I understand this was probably done to speed up john --show by Aleksey.  Maybe the first call of john show should be done without the --format thing to get a more coherent tableview and further calls could be made with the --format to keep the speed ? Or maybe, was it the behaviour that you guys wanted ?

**Comment by math07** [comment]
This issue is not a priority, don't waste time now answering if you are busy.

**Comment by math07** [comment]
@AlekseyCherepanov Was it done on purpose for optimisation ?

**Comment by AlekseyCherepanov** [comment]
On Thu, Jun 04, 2015 at 09:18:21AM -0700, math07 wrote:
> Here is the use case.
> Imagine the .pot file has some already cracked password in it. If we
> open a new file, start a new attack or resume another one with a
> different format, callJohnShow() method call ./john --formatXXX
> --show pw1.txt. In the tableview, the already cracked password from
> the .pot file from format YYY won't appears.

> 1) I understand this was probably done to speed up john --show by
> Aleksey.

No, it is not for speed.

> Maybe the first call of john show should be done without
> the --format thing to get a more coherent tableview and further
> calls could be made with the --format to keep the speed ? Or maybe,
> was it the behaviour that you guys wanted ?

--show means that you have to call it with each format to get all
cracked hashes.

Imagine scenario: you cracked some hashes with --format=YYY, then you
close johnny, open johnny, open the file, and now johnny does not know
that --format=YYY was used previous time.

--show=types can work around that: when johnny opens file, you build
hash table hash->(line in table view) for all variants of canonical
hashes, then johnny reads .pot itself (without --show) and goes
through it checking hashes against the hash table. It won't work
without --show=types that is in jumbo only, but I don't see an
universal solution now.

For much much later: as of core john has a few formats only with
stable format of hashes, johnny might distinguish these hashes on its
own. Though it won't work for .pot with hashes from both core and
jumbo but I guess it is a rear case and it does not seem very
important to me. It is not needed to implement that now.

To call john --show without --format may be an interesting compromise.
It won't load passwords from --format=YYY (unless it is default
format) but I hope --format= option is not used most of the times.

Thanks!

-- 
Regards,
Aleksey Cherepanov

**Comment by shinnok** [comment]
@AlekseyCherepanov So it can be removed or ..?

**Comment by AlekseyCherepanov** [comment]
On Thu, Jun 25, 2015 at 07:51:53AM -0700, Shinnok wrote:
> @AlekseyCherepanov So it can be removed or ..?

I'd say: there is nothing to remove, instead this behaviour is caused
by lack of code. Not sure... I need to check the code to say more
confidently.

Thanks!

-- 
Regards,
Aleksey Cherepanov

**Comment by shinnok** [comment]
@math07 Go ahead and use show without format the first time we load a session and then use the current format from there on. Will this clear the tableview and only show the new ones?

**Comment by AlekseyCherepanov** [comment]
On Fri, Jun 26, 2015 at 01:08:22AM -0700, Shinnok wrote:
> @math07 Go ahead and use show without format the first time we load a session and then use the current format from there on. Will this clear the tableview and only show the new ones?

I think tableview is cleaned on file open.

john --show can be called twice: without --format= and with --format=
if it is specified.

Thanks!

-- 
Regards,
Aleksey Cherepanov

**Comment by AlekseyCherepanov** [comment]
On Fri, Jun 26, 2015 at 11:11:08AM +0300, Aleksey Cherepanov wrote:
> On Fri, Jun 26, 2015 at 01:08:22AM -0700, Shinnok wrote:
> > @math07 Go ahead and use show without format the first time we load a session and then use the current format from there on. Will this clear the tableview and only show the new ones?
> 
> I think tableview is cleaned on file open.
> 
> john --show can be called twice: without --format= and with --format=
> if it is specified.

s/can/might/ . You may want to call it twice.

Thanks!

-- 
Regards,
Aleksey Cherepanov

**Comment by math07** [comment]
Okay now I understand what Aleksey meant. John --show isn't working like I thought. john --show without specifying format will show cracked passwords for the default format ONLY. It won't show all cracked passwords at all. There's no real way to get ALL cracked passwords in the tableview except knowing all formats of the hashes in the file and calling john --show=format1, john --show=format2 etc... It might be too much processing spawning that much john processes...

**Comment by shinnok** [comment]
Ok, this is getting confusing and is a usability concern. How about we ask on the list what we should do about it?

**Comment by shinnok** [comment]
>Okay now I understand what Aleksey meant. John --show isn't working like I thought. john --show without specifying format will show cracked passwords for the default format ONLY. It won't show all cracked passwords at all. 

I just tried this my self and it doesn't confirm. It shows all cracked passwords. Maybe what you were seeing was impacted by the bug fixed in https://github.com/math07/johnny/commit/f9f2b58c9596ea6df2aaf14c3dd3fd6a74f63627.

**Comment by math07** [comment]
> I just tried this my self and it doesn't confirm. It shows all cracked passwords. Maybe what you were seeing was impacted by the bug fixed in math07@f9f2b58.
Did you crack those passwords with --format = (different than default) in JtR ?

**Comment by math07** [comment]
I have a file which is recognized as LM(default), but the true is that they are Nt-old.
john --show pw1.txt
0 password cracked
john --show --format=Nt-old pw1.txt
2021 passwords cracked

**Comment by math07** [comment]
> I have a file which is recognized as LM(default), but the true is that they are Nt-old.
> john --show pw1.txt
> 0 password cracked
> john --show --format=Nt-old pw1.txt
> 2021 passwords cracked


Also, let's add a cracked nsldap in this file.
john --show pw1.txt
0 password cracked
john --show --format=Nt-old pw1.txt
2021 passwords cracked
john --show --format=nsldap pw1.txt
1 password cracked

**Comment by shinnok** [comment]
Is this core or jumbo?

**Comment by shinnok** [comment]
✔ 18:09 ~jtr/jumbo/run$ ./john --show --format=descrypt ../../../passwds/test-hashes.lst 
1:U*U*U*U*
4:*U*U*U*U
5:

3 password hashes cracked, 2 left
✔ 18:09 ~jtr/jumbo/run$ ./john --show --format=md5crypt ../../../passwds/test-hashes.lst 
19:test
20:12345678
21:
25:
26:1234
27:john
28:the
29:ripper
30:aaaaa
31:lapin
32:canard
33:test1
35:manger
36:haut
38:password
41:password

16 password hashes cracked, 10 left
✔ 18:09 ~jtr/jumbo/run$ ./john --show ../../../passwds/test-hashes.lst 
1:U*U*U*U*
4:*U*U*U*U
5:
17:
19:test
20:12345678
21:
25:
26:1234
27:john
28:the
29:ripper
30:aaaaa
31:lapin
32:canard
33:test1
35:manger
36:haut
38:password
41:password

20 password hashes cracked, 28 left

**Comment by math07** [comment]
I'm using jumbo. We seems to get different results based on the format we are using. A raw-sha512 inside a Nt-old file detected as LM don't appear on john --show, 0 cracked password. However , a nsldap inside a Nt-old file detected as LM appears on john --show (but Nt-old hashes don't appear) so only one password cracked. And you do get different results with your md5crypt and descrypt hashes.

**Comment by shinnok** [comment]
How about we relay this information on john-dev?

**Comment by math07** [comment]
I made thread http://www.openwall.com/lists/john-dev/2015/08/13/14
