### ISSUE TITLE
Environment variables & Restoring sessions

### ISSUE THREAD

**Issue by math07** [shinnok/johnny#31]
Currently, when we open a last session, we use --restore and the .rec which doesn't seem to save the things related to environment variables such as OpenMP and other environment variables that we can specify in the field I added to Johnny a few weeks ago requested by Solar. @AlekseyCherepanov Is that correct ?

As part of the multiple session management, I'll save those environment variables to QSettings to restore the UI correctly. When restoring a session, my idea is to put them filled by default(ex: var1=XXX) so the user get the comportment he had last time with this session(ex: the same nb of openMP threads). But the user can still edit with var2=YYY or remove some variables and resume the attack with the changes working(unless other settings like --fork witch are directly written in the .rec and will take effects only if you start a new attack)

**Comment by AlekseyCherepanov** [comment]
Mathieu,

On Wed, Jun 17, 2015 at 08:16:47AM -0700, math07 wrote:
> Currently, when we open a last session, we use --restore and the .rec which doesn't seem to save the things related to environment variables such as OpenMP and other environment variables that we can specify in the field I added to Johnny a few weeks ago requested by Solar. @AlekseyCherepanov Is that correct ?

I don't know how openmp interacts with .rec files. You need to check
it on your own. Or you may ask on john-dev. Thanks!

-- 
Regards,
Aleksey Cherepanov

**Comment by math07** [comment]
> I don't know how openmp interacts with .rec files. You need to check it on your own. Or you may ask on john-dev. Thanks!
I already checked that when we pass a variable to john like that, it isn't kept during sessions, but I wanted to double-check with a experienced john-user if it's the same for all environment variables that we can pass to john.
OMP_NUM_THREADS=8 ./john --format=aix-smd5 --session=bob password.txt
Will run 8 OPENMP THREADS
./john  --restore=bob
Will run 2 OPENMP Threads
But given the fact that john is looking for such settings as environment variables, I'll trust my tests since it's logical that it works this way(and isn't stored in .rec). But Johnny abstracts this concept, user isn't looking for that behavior(especially for the openMP number of threads spinBox which abstract the environment variable concept) so I'll make what I said in the first post as improvement.

**Comment by math07** [comment]
For the records, this is fixed in PR #23

**Comment by shinnok** [comment]
So will this work with resume too? I'm not sure..

**Comment by math07** [comment]
> So will this work with resume too? I'm not sure..

When opening a previous session, it'll load the openMP nb of threads and environment variables from QSettings. If the user don't go change it in the UI, it's gonna work with resume and start new attack. If the user go change it in the UI, it'll resume with the current setting from the UI, not the one from QSetting. Do you want a different behavior ?

**Comment by shinnok** [comment]
Yes this is correct. Closed.
