### ISSUE TITLE
Update french translation before release

### ISSUE THREAD

**Issue by math07** [shinnok/johnny#34]
Reminder : I should update the french translation files before release since we did a lot of changes in johnny since the beggining of GSOC

**Comment by math07** [comment]
This is done unless we change words in the .ui.

**Comment by shinnok** [comment]
I'm making changes in that regard, so better to wait and do another after we freeze. Changes I'm making might also break compatibility with Qt4 so better to do another run for that after the freeze too.

**Comment by math07** [comment]
> I'm making changes in that regard, so better to wait and do another after we freeze. Changes I'm making might also break compatibility with Qt4 so better to do another run for that after the freeze too.

Okay I'll redo translation and recheck centOS 6 after you tell me it's done.

**Comment by math07** [comment]
The french translation has been updated again
