### ISSUE TITLE
Version 2.0 release checklist

### ISSUE THREAD

**Issue by shinnok** [shinnok/johnny#38]
Tasks to do in regards to this release:

1. Resolve #37 #35 #34 #22 #17 #16
2. Update INSTALL distfile with source building instructions for all supported platforms. See #17
3. Prepare OS X and Windows redistributables and test them
4. Freeze changes and tag version 2.0 in git
5. Prepare final redistributables
6. Add CHANGELOG distfile
7. Revise Johnny's main Wiki page on openwall.info
8. Write announcement e-mail (should be sent to both john-users and john-dev); include details on what's new, what's changed, what's ahead and where to get packages, source and more info
9. After review of the announcement e-mail, proceed to public unvelining

NB: Some tasks are to be handled by me, pay attention to the Assignee tag for issues or ask me directly

**Comment by shinnok** [comment]
I also have some of my tasks pending from the Wiki page. I'm going to handle what I can until we get close to step 4. and let you know when I'm done.

**Comment by math07** [comment]
Bad news, I guess you remember the CTRL_C stuff that we worked so hard on :(
Riche have 2 PC with Windows 7 64 bits, he says one is pausing correctly with a jumbo build that has the correct CTRL_C handling stuff from your PR and one PC isn't and give the John crashed error. He talks about it on the list.

**Comment by shinnok** [comment]
@math07 I've created the v2.0 milestone in Github issues and assigned the outstanding tasks to it. It's a much better tracking method, rather than keeping a list of issues like I did in item 1. up there.

**Comment by shinnok** [comment]
The next thing to do as part of this is to start writing the announcement e-mail that we should send to both john-dev and john-users. I'd like you to start drafting a first version of it, then you can share it to me via e-mail for refinement.

**Comment by math07** [comment]
> The next thing to do as part of this is to start writing the announcement e-mail that we should send to both john-dev and john-users. I'd like you to start drafting a first version of it, then you can share it to me via e-mail for refinement.

Do you think that we'll have negative reports from users given the fact that the sources/binaries provided on http://www.openwall.com/john/ are not the "best choice" for johnny. For example, 1.8.0 source is provided but john on Windows isn't working and the jumbo sources provided don't have --show=types(format suggestion) ?

**Comment by shinnok** [comment]
There's not much we can do at this point in regards to that. This will get somewhat sorted out with the next releases. In the meantime we have to be clear in the announcements and wiki pages on the fact that certain Johnny functionalities are only available with the Jumbo version as well as clear out the distinction between john core and john jumbo.

**Comment by math07** [comment]
I sent you the draft on your admin email.

**Comment by shinnok** [comment]
Release done. Good job Mathieu.
