### ISSUE TITLE
Add About widget and corresponding menubar action

### ISSUE THREAD

**Issue by shinnok** [shinnok/johnny#39]
Similar to what has been done here https://github.com/Tarsnap/tarsnap-gui/issues/15.

**Comment by math07** [comment]
I added that. However, the QDesktopServices::openUrl() is so damn slow on my Fedora VM and isn't really working, not sure if we should keep the Check for update button.

**Comment by shinnok** [comment]
Don't worry about a single case like that, which is also outside of our control. If it works just fine on the other platforms/desktop, which I know it is, there's no reason to change anything.
