### ISSUE TITLE
Johnny with installer should automatically detect bundled john

### ISSUE THREAD

**Issue by math07** [shinnok/johnny#50]
Here is a problem that we have at the moment. Imagine the release folder is as follow.
./johnny.exe (or any other executable format)
./XXX.dll
./yy.dll
./JohnTheRipper/run/john.exe

We already search for john.exe in the same directory because when you have an installer, it should be easy to make johnny works without configuration. However, since the m_pathToJohn setting is system-wide,  if another john older version was specified in the past by the user, or for example comes from another release or folder of johnny, we'll remember an existing old path and we won't do our auto-detect. So we  bundle a new john with johnny, but it's not gonna get used.

I'm not sure if I was clear enough to make you understand what I mean.

**Comment by shinnok** [comment]
The only reasonable solution would be to default the first order of search with a hardcoded path to ./JohnTheRipper/run/ (this is only for the case where there's no valid setting stored for it). If that doesn't get found than revert to the existing method of search.

However, I'm not sure if we should bundle JtR with our installer yet, I need to check on the list first and then come back to this with a resolution.

From your installer work so far, would this be easy enough?

**Comment by math07** [comment]
> From your installer work so far, would this be easy enough?

If we just want to put the JohnTheRipper folder in the installed johnny directory, pretty easy.

**Comment by math07** [comment]
> The only reasonable solution would be to default the first order of search with a hardcoded path to ./JohnTheRipper/run/ (this is only for the case where there's no valid setting stored for it). If that doesn't get found than revert to the existing method of search.

What do you mean by " when there's no valid setting stored for it" ? In this issue, there might be a valid setting stored but i can be a old JtR version from a previous installation of johnny that we should ignore since the one currently bundled is more recent.

**Comment by shinnok** [comment]
Given the amount of changes we've done so far, I don't think we should worry about that and the only reasonable course of action if one is "upgrading" would be to purge his existing configs and start from scratch.

**Comment by math07** [comment]
> Given the amount of changes we've done so far, I don't think we should worry about that and the only reasonable course of action if one is "upgrading" would be to purge his existing configs and start from scratch.

Okay, let's close this issue. Also, since the discussion on john-dev seems to request not bundling jumbo with johnny, this won't happens.
