### ISSUE TITLE
[Windows] Forbidden file name for session

### ISSUE THREAD

**Issue by math07** [shinnok/johnny#51]
I'm using latest jumbo official release 1.8.0.6-jumbo-1 (the only official release which contains the CTRL_C stuff) on Windows. I don't know what's  going on with encoding. The character ":" that we use in our session name is written as a weird character as you can see in the screenshot. This prevents our session history feature to work as the .rec is never found by johnny since it doesn't have the same name ..
![image](https://cloud.githubusercontent.com/assets/9955284/8392632/51ea6d26-1cbe-11e5-8e73-fd43bf187044.png)

**Comment by math07** [comment]
The issue is on our side, Windows, don't allows to put the ":" character in file names. WTF ?

**Comment by math07** [comment]
Which character could be used for the time instead of the illegal on Windows ':' ? It was the most easy to understand for the user, could we put 06-27-15-11h16.10 ?

**Comment by shinnok** [comment]
This is occurring on OS X too, though at some level it gets replaced by '/'. The the colon character is forbidden in those respective file systems. Let's just replace with a single dash '-'.

**Comment by math07** [comment]
Okay fixed in e285d52 . The format is now MM-dd-yy hh-mm-ss , I had to add a space since john don't allows number only session name (and - doesn't count).

**Comment by shinnok** [comment]
Hmm, are you sure Solar's regex filters against that? I'm not particularly fond of the white space in the session file name.

**Comment by math07** [comment]
> Hmm, are you sure Solar's regex filters against that? I'm not particularly fond of the white space in the session file name.

I'm sure that one of the somewhat-recent version of JtR that I tested on Windows count number-number-number as a numeric-char only in session name JtR error. I don't remember which version it was (probably a random one from git, not a official release). I'll check 1.8.0.6-jumbo-1 release and latest bleeding jumbo and master branches to see if it behaves correctly with that use case.

**Comment by shinnok** [comment]
Can you please check against Solar's amended regex fix? I'm not particularly fond of the whitespace, as a last resort it should be replaced with an underscore.

**Comment by math07** [comment]
With session name /07-02-15-11-59-40, no problem with numeric char only, let's do what you want without space. The version I tested which didn't work with space was probably a random one
Latest master(core/john) : Works
1.8.0.6-jumbo-1 : Works
Latest bleeding-jumbo : Works
john 1.8.0 : Works (but not recommended in windows since it doesn't have the CTRL_C fix
