### ISSUE TITLE
Platform testing checklist

### ISSUE THREAD

**Issue by shinnok** [shinnok/johnny#53]
Let's check off this list the platforms that have been tested and are confirmed(via either source or redistributable installer):
1. Windows 7 and 8; .msi installer; Based on latest Qt5
2. OS X Mavericks and Yosemite; .dmg package; Based on latest Qt5
3. Linux(Ubuntu, Debian, Mint, Fedora, various distros); source build
4. Compatibility with Qt as low as version 4.6.2 (for old Linuxes and OS X Leopard);

**Comment by shinnok** [comment]
@math07 We need to cross items off that list. Please do so with the platforms you've tested on already.

**Comment by math07** [comment]
Windows 7 and 8.1 CHECK
OS X Mavericks CHECK
CentOS 6 (with qt 4.6.2) CHECK
Fedora CHECK
Ubuntu CHECK

**Comment by shinnok** [comment]
Please include distro version numbers/code names too.

**Comment by shinnok** [comment]
You should include the OS X build steps to INSTALL, even if we provide a dmg.

**Comment by math07** [comment]
> Please include distro version numbers/code names too.

I updated the post with more info

**Comment by shinnok** [comment]
Windows 7 - both installer and source build
OS X Yosemite - both dmg and source build

**Comment by shinnok** [comment]
This is enough testing for now, any other potential issues should be handed to us by users.
