### ISSUE TITLE
Update Openwall wiki for release

### ISSUE THREAD

**Issue by math07** [shinnok/johnny#55]
I updated openwall wiki, let's use this issue to give me your feedback.
http://openwall.info/wiki/john/johnny

**Comment by shinnok** [comment]
Let's update the Features category to better reflect the current state.

**Comment by math07** [comment]
I remived 8 and 11 and added those points:  
  ability to resume any previously started session via session history,
    suggest the format of each hashes,
    try lucky guesses with password guessing feature,
    available in english and french,
    allows you to set environment variables for each session directly in Johnny
