### ISSUE TITLE
Search/Filter inside the Passwords tab table view

### ISSUE THREAD

**Issue by math07** [shinnok/johnny#56]
I didn't implement the feature but I make a draft of the .ui based on what you said on the list in the thread Mathieu's weekly report 8. What do you think of that @shinnok ? Imagine that there is one checkbox from PR #54 in each row of the table view.
![capture d ecran de 2015-07-06 23 05 27](https://cloud.githubusercontent.com/assets/9955284/8537981/152b49aa-2434-11e5-8e10-e9e426f157b8.png)

**Comment by math07** [comment]
PS : It's a QGroupBox but they don't have lines in Fedora

**Comment by math07** [comment]
I'm not sure if the wording and layout are correct, my idea was to put : 
1) buttons which will select all hashes/unselect all hashes from the file which are in no way connected to the search field.
2) buttons that select/unselect based on the search results.

**Comment by math07** [comment]
Or maybe version 2 without QGroupBox which slightly take less room at the top.
![capture d ecran de 2015-07-07 15 47 53](https://cloud.githubusercontent.com/assets/9955284/8555712/bc29e4c4-24bf-11e5-815e-d63ae19df9f7.png)

**Comment by math07** [comment]
Or maybe any other idea you have

**Comment by shinnok** [comment]
Yes we should use the checkboxes from PR #54 for the actual filtering.

I'm not sure we need the select buttons(Select all, Unselect all), those actions should be available via the common table view selection methods and with a default action of select/unselect on spacebar press or right click context menu. All we need is an extra checkbox called "Show only selected/Show all" that switches the table view for easier preview of big password files.

The "User", "Password" column selectors should all be checked by default.

**Comment by math07** [comment]
> I'm not sure we need the select buttons(Select all, Unselect all), those actions should be available via the common table view selection methods and with a default action of select/unselect on spacebar press or right click context menu.
The select buttons are doing "check all checkboxes", "uncheck all checkboxes". I can put those actions in the table view context menu but what do you mean by  "those actions should be available via the common table view selection methods" ?

**Comment by shinnok** [comment]
I meant the user should select items by the usual means of QTableWidget. And then for check/uncheck just press spacebar or right click context menu with action "Select/Unselect". We shouldn't need extra buttons for any of that. For clearing a filter just the QComboBox clear button should suffice.

Press control+a in the table view or left most upper header section (left to User) to understand why we don't need extra buttons.

**Comment by shinnok** [comment]
The filter actually removes the irrelevant items from the view by the way and only displays the relevant ones. It doesn't actually affect the attacked hashes until the users checked/unchecked some rows.

**Comment by math07** [comment]
> The filter actually removes the irrelevant items from the view by the way and only displays the relevant ones. It doesn't actually affect the attacked hashes until the users checked/unchecked some rows.

Oh I thought the filter was also checking/unchecking rows. Thanks for the clarification

**Comment by math07** [comment]
> I meant the user should select items by the usual means of QTableWidget. And then for check/uncheck just press spacebar or right click context menu with action "Select/Unselect". We shouldn't need extra buttons for any of that

Okay, I'll implement it so select/unselect all checkboxes from the context menu affects all currently VISIBLE rows instead of always affecting the whole tableview.

**Comment by math07** [comment]
Since you talked about removing the buttons and putting only a checkbox, I guess that you want dynamic filtering : i.e everytime a user enter a new letter/remove in the QLineEdit we look again in all fields if it contains the corresponding string. (Signal textEdited http://doc.qt.io/qt-4.8/qlineedit.html#textEdited). Do you think that it'll affect performance negatively on whole file if we use this "naive" algorithm ?

**Comment by math07** [comment]
> Since you talked about removing the buttons and putting only a checkbox, I guess that you want dynamic filtering : i.e everytime a user enter a new letter/remove in the QLineEdit we look again in all fields if it contains the corresponding string. (Signal textEdited http://doc.qt.io/qt-4.8/qlineedit.html#textEdited). Do you think that it'll affect performance negatively on whole file if we use this "naive" algorithm ?

Regarding this, I read that using QSortFilterProxyModel (which I already use for the sorting) makes filtering pretty fast. For example, a guy on stackoverflow said hiding/showing manually rows in tableview was fast for 3000 rows but for example really really slow for 600 000 rows. However, with QSortFilterProxyModel, it was fast at 600 000 rows. I'll give it a try and test by myself. https://forum.qt.io/topic/6765/hiding-rows-in-qtableview-seems-to-be-slow/3

**Comment by math07** [comment]
I followed the example given in the qt documentation http://doc.qt.io/qt-5/qtwidgets-itemviews-customsortfiltermodel-example.html to implement filtering with QSortFilterProxyModel. To test performance, I copy pasted multiple occurences of the md5 PHDays password file to get around 100 000 hashes/rows in Johnny. The filtering is indeed really fast based on the code from PR #64. However, if you type fast letter by letter d y n a m i c _ 0 for example, you can see a small delay in the UI because we do 9 filtering operations consecutively (e.g after each new letter is added to the LineEdit). For example, you type dynamic_0 really fast, but you will see on the line edit d-small wait- y wait n wait etc. appears in the UI. I think you should test my PR to see what I mean and see the delay for yourself. With a button, it'd probably be perfect because filtering is really fast. Please note that I'm currently only parsing the first 3 rows(user/password/hash) and I didn't implement the logic of the checkboxes but I already have my plan to do that, it's gonna be easy. 

If we want to keep it dynamic(without button), we could try to implement a caching algorithm to reuse the previous results like described here http://www.qtcentre.org/threads/40471-QSortFilterProxyModel-quite-slow-for-bigger-data-models . I don't think that QSortFilterProxyModel reuse previous results. However, it'd not make any difference if you write dynamic_0$d6 and all the hashes in your file are dynamic_0 since you'll have all your rows in your cache since they all contains dynamic_0$. For some cases, it'd be better. After that, we could use threading but I saw on the qt-forum that it's not that easy with QSortFilterProxyModel built in filtering and that we should implement our own things.

**Comment by shinnok** [comment]
Use QLineEdit::editingFinished() if the model is bigger than 10k hashes and set the placeholder text to "Press return to apply filter".

**Comment by math07** [comment]
> Use QLineEdit::editingFinished() if the model is bigger than 10k hashes and set the placeholder text to "Press return to apply filter".

1) Okay. PlaceHolderText property was introduced in Qt 4.7. I'll implement my own method.

**Comment by math07** [comment]
> 1) Okay. PlaceHolderText property was introduced in Qt 4.7. I'll implement my own method. 

After much thinking, I'm not sure a placeholder text is appropriate given the described use case. 
1) User opens a file with 2k hashes and he plays with the dynamic filter.
2) He opens a file with 100k hashes. He won't see the placeholder text unless we clear his filter text(example : dynamic_0). So he won't know that the behavior of the filter changed. Will user appreciate that we clear his filter text when he opens a new file ?

**Comment by shinnok** [comment]
We definitely need to reset the filters and checkboxes when a new session is loaded.

**Comment by math07** [comment]
> We definitely need to reset the filters and checkboxes when a new session is loaded.

Okay good, i'll do that

**Comment by shinnok** [comment]
I'm satisfied with the implementation, good job. Closed.
