### ISSUE TITLE
Default hash format used in attack by JtR

### ISSUE THREAD

**Issue by shinnok** [shinnok/johnny#61]
We need to display the default hash format type in the progressbar (and elsewhere), in the case where the user didn't specify one.

**Comment by math07** [comment]
Do you mean writing 1) --format=default or 2) parsing the console log to get the format chosen by john ? I think you mean 2) but I want to make sure.

**Comment by shinnok** [comment]
Not that confident in the usefulness of 2) since the user will find out what format is being attacked only after he starts a session, which might be half-assed;
I'll ask on the list about this.

**Comment by jfoug** [comment]
The default is the hashtype of the first line in the file that satisfies a format->valid().

John will take each line, and run it through the prepare() and valid() for each possible hash format. As soon as one returns true on a line, then that is the hash format used.

**Comment by AlekseyCherepanov** [comment]
On Wed, Jul 15, 2015 at 05:40:41PM +0300, Aleksey Cherepanov wrote:
> On Wed, Jul 15, 2015 at 07:35:54AM -0700, jfoug wrote:
> > The default is the hashtype of the first line in the file that satisfies a format->valid().
> > 
> > John will take each line, and run it through the prepare() and valid() for each possible hash format. As soon as one returns true on a line, then that is the hash format used.
> 
> --show=types saves the order: so the first format in the first lines
> with 1+ formats listed is the default.

As I wrote on john-dev, it is not the best solution. Thanks!

-- 
Regards,
Aleksey Cherepanov

**Comment by shinnok** [comment]
@math07 When you get to this do it on another branch/PR so I can integrate the outstanding ones.

**Comment by math07** [comment]
Important information from the decision from the list:
For core approach, create a new JohnHandler that will run every time new password files are opened(thus a new session) and grep the output for the default attack format. Use it in the UI and elsewhere.
Use magnum's approach , `john -stdin hashfile <<< ""` , if it is the minimal overhead one.

**Comment by math07** [comment]
@shinnok  Where do you want to write the default format in the UI ? In the combobox Auto-detect (md5crypt) or on a different label ?

**Comment by shinnok** [comment]
In the combo and in the progress bar too, just like we do now.

**Comment by math07** [comment]
There's something that I didn't think of : every time a user unselect a hash/uncheck a row, it has the potential of changing the default format since the file changed ...

**Comment by shinnok** [comment]
Can you fix it?

**Comment by math07** [comment]
> Can you fix it? Are we starting a new attack every time after selection has changed? We can't resume anyway.

We start new attack only when user push the stop attack/ start attack button. Unchecking rows during a running attack is the same as changing the mode or any other attack parameter, it only take effects on the next run. Was it what you had in mind ?

Regarding the actual issue,  I could fix it by recalling magnum --stdin everytime user uncheck a row. That's the only way if we don't want the comboBox to show wrong info. 

Here is my concern. I didn't get any report from 2.1 except from Don(newagels) so it might not reflect the vision of everyone. He is using Johnny with a 1 200 000 hash file(1.2 milion) . On that level, show=types from Aleksey is quite slow(several minutes, maybe 10, probably more?), and depending on the format in the file john --show may take 1 minute. And the CPU is at 100% during those time. So he closed johnny. I recommended him to separate his big file in smaller files and he agreed. However, maybe people in general already think we are using john process with too much cpu for stuff they don't need. I have no idea. Maybe starting a new john process everytime someone uncheck a row is too much.

**Comment by math07** [comment]
One thing I must make clear we don't use more process in 2.1 than 2.0, it's just that the comment was made after our 2.1 release.

**Comment by shinnok** [comment]
I think it's ok to require starting a new attack if the row selection state has changed. We just have to make this obvious in the UI.

**Comment by math07** [comment]
What about the comment from Don ?

**Comment by math07** [comment]
> I think it's ok to require starting a new attack if the row selection state has changed. We just have to make this obvious in the UI.

Not sure what you mean there ? Leave the code as is and write info into the UI that default format isn't updated when you uncheck row ?

**Comment by shinnok** [comment]
We're a bit confused. Let's separate this discussion into the two issues it entails:
1. Selection status won't be reflected on attack resume, just new attacks. Is this how this works now? We should make this obvious if so?
2. Default format might change upon selection modification. All we need to do is call the default format handler with a new attack?

**Comment by math07** [comment]
> 1. Selection status won't be reflected on attack resume, just new attacks. Is this how this works now? We should make this obvious if so?

Yes exactly. Is it OK if we change the tip label to(without capitals) "Tip: If you change attack options OR THE SELECTED HASHES, you need to Start a new attack for them to come into effect." or it should be in the password tab page ?

> 2. Default format might change upon selection modification. All we need to do is call the default format handler with a new attack?

I mean there isn't always an attack going on. You can uncheck rows one at a time for a few minutes without wanting to stop the current attack or start an attack at all. In those cases, the label on the format combo Box might not be good. What's your position on the comment from Don that I put a few messages before ? If you think we don't use too much CPU, we could call default format handler every time a row is unchecked to update the combo box.

**Comment by shinnok** [comment]
>Yes exactly. Is it OK if we change the tip label to(without capitals) "Tip: If you change attack options OR THE SELECTED HASHES, you need to Start a new attack for them to come into effect." or it should be in the password tab page ?

Yes. In the Passwords tab, unless we can set tooltips on the checkboxes...

>I mean there isn't always an attack going on. You can uncheck rows one at a time for a few minutes without wanting to stop the current attack or start an attack at all for that time. In those cases, the label on the format combo Box might not be good. What's your position on the comment from Don that I put a few messages before ? If you think we don't use too much CPU, we could call default format handler every time a row is unchecked to update the combo box.

I think doing anything in this regards will complicate things and we don't know what users would expect. If I think more of it, keeping the format selection is the way to go for now, since it can't harm. When the user starts a new attack with modified selections, he will find himself in one of 2 positions:

1. All hashes are already cracked for the selected format; Attack ends promptly.
2. Some or all hashes are uncracked; Attack proceeds.
3. Selected hashes don't include any of the selected format; Attack ends promptly.

We'll know better once a user complains about it I assume.

**Comment by math07** [comment]
> If I think more of it, keeping the format selection is the way to go for now, since it can't harm.

1 ) I added the tooltip. 2) Not sure if the quoted phrase means that we keep the m_defaultFormat JohnHandler calls AS IS ? I didn't change it.

**Comment by shinnok** [comment]
Let's leave as is for now, we can adjust post user feedback.
