### ISSUE TITLE
[UI-Usability] Don't put ComboBox everywhere

### ISSUE THREAD

**Issue by math07** [shinnok/johnny#63]
In all settings, we use combo box in place where there should be line edit. In fact, there is the drop down icon which tell the user that there might be predefined values(like the format comboBox) but in fact there aren't for almost all our options.

**Comment by math07** [comment]
Maybe it's not a real improvement, I leave it to you to decide shinnok.

**Comment by shinnok** [comment]
Yes this was something I was going to do anyway. I'll leave it to you then.
