### ISSUE TITLE
OS X dmg package has weird title

### ISSUE THREAD

**Issue by shinnok** [shinnok/johnny#67]
When opened in Finder, the title on the volume is /Users/admin/etc..

It should be just Johnny, can you look into it? See what you did wrong with the macdeployqt command.

PS: If the commands used are more than one line, it might be useful to create a small shell script and add it to the repo.

**Comment by math07** [comment]
Here is something I wrote for the records in #42. I think those new steps work but I'm not 100% sure of where you saw the /Users/admin stuff. I'll upload a new .dmg with current/master to the wiki in the next minutes, so please confirm it's fixed or make me a screenshot. Thanks.

For the records, to make a .dmg with correct title, you have to follow these exact steps.
1. Place yourself in the build directory of Johnny (where the .app is).
2. /Users/admin/Qt5.4.1/5.4/clang_64/bin/macdeployqt Johnny.app verbose=2 -dmg

If you do the opposite, I think that you'll get wrong title in finder. So don't use those steps:
1. Place yourself in the directory of macdeployqt
2. ./macdeployqt /Users/admin/build-johnny-Desktop_Qt_5_4_1_clang_64bit-Release/johnny.app verbose=2 -dmg

**Comment by shinnok** [comment]
The title is correct now. However, you shouldn't have replaced the 2.0 package in the wiki page, please undo.

**Comment by math07** [comment]
I no more have the 2.0 package, I'll checkout v2.0, rebuild and reupload.

**Comment by shinnok** [comment]
Please do that and then close this issue.

**Comment by math07** [comment]
Done
