### ISSUE TITLE
Path to john setting improvement

### ISSUE THREAD

**Issue by shinnok** [shinnok/johnny#68]
We need a validator that checks if the path that is being set is a valid existing file, readable and executable. Further more we could check if it is john indeed by greping the output of ./john with no args and also checking to see if it's jumbo or core right there and then reconsider the UI.

**Comment by shinnok** [comment]
We could easily upgrade the m_johnVersionCheck to do all of this. We should connect it to either textEdited() or editingFinished() of the lineEdit.

**Comment by math07** [comment]
What will the validator do ? show lineEdit background in red until a valid john path is specified and then show it in green ? what other things would it do?

**Comment by math07** [comment]
it could be a red   X at the right of the line edit when invalid and green checkmark when valid

**Comment by shinnok** [comment]
I'm thinking just making the text red or black via QSS. In addition we should also have another label bellow it that states:
"Not a valid path to John."
"John core/jumbo version xx detected."

**Comment by math07** [comment]
Closed, you can reopen it if you have new comments.
