### ISSUE TITLE
Release v2.1 checklist

### ISSUE THREAD

**Issue by shinnok** [shinnok/johnny#70]
Tasks to do in regards to this release:

* Freeze changes and tag version 2.1 release
* Test source build on all supported platforms
* Prepare updated OS X and Windows redistributables and test them
* Add 2.1 entry to CHANGELOG and update INSTALL
* Update Johnny's main Wiki page on openwall.info
* Write announcement e-mails. One for john-users done by @math07. I'll forward that to john-dev as I did previously.

**Comment by shinnok** [comment]
We can do the freeze after we are done with issue #61.

**Comment by math07** [comment]
Will we keep 2.0 stuff on the wiki or not ?

**Comment by shinnok** [comment]
Keep the redistributables history for now, add 2.1 category. The "Features" paragraph, I don't like it in the current form. Either improve it in such a way that it is more relevant and descriptive or remove it and just add links to CHANGELOG.

**Comment by shinnok** [comment]
We could also do with 2 Ubuntu screens. I can add OS X ones.

Screens are the first thing new comers/potential users look for and they have to be good and attractive. ;-)

**Comment by math07** [comment]
> We could also do with 2 Ubuntu screens. I can add OS X ones.

Do you want 2 fedora + 2 ubuntu + 2 OS X or 2 ubuntu + 2 OS X ?

**Comment by shinnok** [comment]
You  can keep the Fedora ones.

**Comment by shinnok** [comment]
Are you using the windeployqt tool for preparing the installer dir on Windows? I just learned of it, it's the analog of the macdeployqt tool and should ease out the task.
http://doc.qt.io/qt-5/windows-deployment.html

**Comment by math07** [comment]
> Are you using the windeployqt tool for preparing the installer dir on Windows? I just learned of it, it's the analog of the macdeployqt tool and should ease out the task.
> http://doc.qt.io/qt-5/windows-deployment.html

No, I don't use it. We don't have QML imports, plugins and our translations are directly into the executable so the normal johnny.exe from qmake; make; with release flag. I still have the DLLs from johnny 2.0 so it's just a matter of overwriting johnny.exe with the new one and calling the installer framework.

**Comment by math07** [comment]
> Tasks to do in regards to this release:
> 
> Freeze changes and tag version 2.1 release
> Test source build on all supported platforms
> Prepare updated OS X and Windows redistributables and test them
> Add 2.1 entry to CHANGELOG and update INSTALL
> Update Johnny's main Wiki page on openwall.info
> Write announcement e-mails. One for john-users done by @math07. I'll forward that to john-dev as I did previously.

Done
