### ISSUE TITLE
Bad interval pick cracked default value

### ISSUE THREAD

**Issue by math07** [shinnok/johnny#83]
It's not rare that john --show takes more than 15 seconds to finish depending on the format and the number of cracked password in the .pot file. If an attack is currently running, the timer is called every 15 seconds(default) and it doesn't finish in 15 seconds so we terminate it, a new john --show starts, it doesn't finish, we terminate it again etc.. so we never get the cracked passwords in the table view. When the user pause attack, we stop the timer and we get the cracked password from john --show which confirm this behavior.

Aleksey used to put it by default at 600, but then you put it at 15 in commit 58a1751. I guess we could find a compromise because a normal user won't think about modifying that value if he doesn't see his cracked password.

**Comment by shinnok** [comment]
How big is your password table?

**Comment by shinnok** [comment]
Maybe the solution would be to not kill the john show handler in the first place, except from quitting the app of course.

**Comment by math07** [comment]
> How big is your password table?

My password table has 19 000 hashes. And I have like 3000 of them cracked in my .pot file.

> Maybe the solution would be to not kill the john show handler in the first place, except from quitting the app of course.

Maybe, do you think john --show has high chance of hanging/requiring us to manually kill it ? We'll loose our protection against that

**Comment by shinnok** [comment]
Are you sure it does take more than 15 seconds for 19k hashes? It seems quite a lot..

**Comment by shinnok** [comment]
BTW, If it hangs, it's not our problem, it should be fixed upstream.

**Comment by math07** [comment]
> Are you sure it does take more than 15 seconds for 19k hashes? It seems quite a lot..

Without johnny and other big process running(like an attack), directly on the terminal john --show takes 30 seconds for my file.  But I don't know which factors is related to that, I think that I got better results on other bigger files/or similar size.
