### ISSUE TITLE
Release v2.2 checklist

### ISSUE THREAD

**Issue by shinnok** [shinnok/johnny#88]
Tasks to do in regards to this release:

*Complete 2.2 milestone
*Freeze changes and tag version 2.2 release
*Test source build on all supported platforms
*Prepare and test updated OS X and Windows redistributables
*Add 2.2 entry to CHANGELOG and update INSTALL
*Update Johnny's main Wiki page on openwall.info; also add 2 Windows screens
*Write announcement e-mails. One for john-users done by @math07. I'll forward that to john-dev as usual.

**Comment by shinnok** [comment]
Mathieu, take some time to write this announcement e-mail as your GSoC completion follow up. Write a summary of your experience and of Johnny's gain this summer as part of your efforts. Also let us know if you plan to stay involved at some level and if you plan on participating again next year.

**Comment by shinnok** [comment]
>*Update Johnny's main Wiki page on openwall.info; also add 2 Windows screens

Regarding that, add the two Windows screens when you test the redistributable and one extra for Ubuntu, this way we have 2 screens for each platform, for consistency.

**Comment by math07** [comment]
This task is completed. Thanks Shinnok for your mentorship and your help this summer :)
