### ISSUE TITLE
chmod a-x resources/icons/*.png

### ISSUE THREAD

**Issue by frank-dittrich** [shinnok/johnny#96]
Some png files are "executable". (May be they have been created on a FAT file system on Windows)

**Comment by math07** [comment]
I can run chmod a-x on them and commit the change if you want.

**Comment by shinnok** [comment]
Go ahead, thanks!

**Comment by math07** [comment]
Done. I'm curious Frank and Shinnok, what is the possible attack vector of this problem ? Also, I guess it applies to all image format or all files that have no good reason to be executable !

**Comment by frank-dittrich** [comment]
I think in this case there isn't much of a risk.
It's more a matter of consistency (or paranoia).
