### ISSUE TITLE
Add button to clear Log

### ISSUE THREAD

**Issue by JPaulMora** [shinnok/johnny#98]
After many sessions, log gets too big and looses autoscroll ability. This makes me scroll down every time output is generated.

**Comment by math07** [comment]
Nice suggestion. I fixed it in the source code. Are you building johnny from source or using an installer ? If you are building the software from source, you can get the new code here https://github.com/shinnok/johnny/archive/master.zip

**Comment by JPaulMora** [comment]
Awesome! Thanks a lot. BTW, I used the Johnny embeded in Kali but it lacks the "fork option" is it a Kali problem or a Johnny>Linux problem? if its the later I could make another issue just so this doesn't get too far off topic.

**Comment by shinnok** [comment]
@JPaulMora  What version of Kali are you running and what version of Johnny is in there? I see that they upgraded to this upstream latest 2.2 last December:
http://git.kali.org/gitweb/?p=packages/johnny.git;a=summary
